version: "3"

services:
  nginx:
    image: nginx:stable
    container_name: nginx
    ports:
      - "6666:80"

    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf
      - ./dist:/home/dist
